apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: lkb3u5mfw-java-quarkus
  janus-idp.io/tekton: lkb3u5mfw-java-quarkus
  backstage.io/kubernetes-id: lkb3u5mfw-java-quarkus
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: lkb3u5mfw-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
